server:
  port: 5556

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/board_of_ads
    username: root
    password: root
    initialization-mode: always

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: false
        jdbc:
          timezone: UTC

  mail:
    host: smtp.yandex.ru
    port: 465
    username: echopride@yandex.ru
    password: terror333
    protocol: smtps
    debug : true

jwt:
  secret: boardofads

jhipster:
  mail: # specific JHipster mail property, for standard properties see MailProperties
  from: kunaev993@gmail.com
  base-url: http://127.0.0.1:5556

security:
  oauth2:
    client:
      clientId: 670394210267367
      clientSecret: 031df2213df96eb1bc72d87fad3cdbd3
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

  auth_yandex:
    client_id: 2561bd17ecc1441d9c2461d780690cae
    client_secret: cc96fba5ab674d159b7d191215e1697b
    response_type: code
    display: popup
    redirect_url: http://localhost:5556/yandex_auth
    auth_url: https://oauth.yandex.ru/authorize
    token_url: https://oauth.yandex.ru/token
    user_info_url: https://login.yandex.ru/info

  auth-vk:
    client_id: 7604924
    client_secret: acpHC7p5T746jYx17yz1
    response_type: code
    redirect_url: http://localhost:5556/vk_auth
    auth_url: http://oauth.vk.com/authorize
    token_url: https://oauth.vk.com/access_token
    users_get_url: https://api.vk.com/method/users.get
    scope: email
    display: popup
    fields: photo_100
    version: 5.124


logging:
  file:
    name: log/board_of_ads.log
    max-size: 1024KB
    max-history: 5
  level:
    root: WARN
    org.springframework.web: WARN
    org.hibernate: WARN
    com.board_of_ads: INFO


